export const LOAD_POST_COMMENTS = 'post/LOAD_POST_COMMENTS';
export const LOAD_POST_COMMENTS_SUCCESS = 'post/LOAD_POST_COMMENTS_SUCCESS';
export const LOAD_POST_COMMENTS_FAILURE = 'post/LOAD_POST_COMMENTS_FAILURE';
