export const LOAD_PROFILE_INFO = 'profile/LOAD_PROFILE_INFO';
export const LOAD_PROFILE_INFO_SUCCESS = 'profile/LOAD_PROFILE_INFO_SUCCESS';
export const LOAD_PROFILE_INFO_FAILURE = 'profile/LOAD_PROFILE_INFO_FAILURE';
export const LOAD_PROFILE_PHOTOS = 'profile/LOAD_PROFILE_PHOTOS';
export const LOAD_PROFILE_PHOTOS_SUCCESS =
  'profile/LOAD_PROFILE_PHOTOS_SUCCESS';
export const LOAD_PROFILE_PHOTOS_FAILURE =
  'profile/LOAD_PROFILE_PHOTOS_FAILURE';

export const TOGGLE_IS_FETCHING = 'profile/TOGGLE_IS_FETCHING';
